<?php

declare(strict_types=1);

use FortNine\ShoppingCartTest\Api\Data\ConfigInterface;

/**
 * @var \FortNine\ShoppingCartTest\Block\Cart $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="shopping-cart-test">
  <h1>Shopping Cart Test (Magento)</h1>

  <nav class="section-nav">
    <strong>Catalog</strong>
    <a href="<?= $escaper->escapeUrl($block->getUrl(ConfigInterface::URL_CART_VIEW)) ?>">Your Cart</a>
  </nav>

  <section class="catalog">
    <h2>Catalog</h2>
    <div class="cards">
      <?php foreach ($block->getCatalog() as $product): ?>
        <article class="card">
          <h3><?= $escaper->escapeHtml($product['name']) ?></h3>
          <p>SKU: <?= $escaper->escapeHtml($product['sku']) ?></p>
          <p>$<?= number_format((float) $product['price'], 2) ?></p>
          <form method="post" action="<?= $escaper->escapeUrl($block->getUrl(ConfigInterface::URL_CART_ADD)) ?>">
            <input type="hidden" name="form_key" value="<?= $escaper->escapeHtmlAttr($block->getFormKey()) ?>">
            <input type="hidden" name="sku" value="<?= $escaper->escapeHtmlAttr($product['sku']) ?>">
            <input type="number" min="1" max="50" name="qty" value="1">
            <button type="submit" class="btn-add-to-cart" >Add To Cart</button>
          </form>
        </article>
      <?php endforeach; ?>
    </div>
  </section>
</div>
